- name: Install Homebrew Dependencies
  hosts: all
  become: yes
  tasks:
    - name: Install Dependencies
      apt:
        name:
          - build-essential
          - curl
          - file
          - git
        update_cache: yes

- name: Manage Homebrew
  hosts: localhost
  connection: local
  tasks:
    - name: Check if Homebrew is installed
      command: /home/linuxbrew/.linuxbrew/bin/brew --version
      register: brew_installed
      ignore_errors: yes

    - name: Install Homebrew
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/brew
      when: brew_installed.failed

    - name: Add Homebrew to Bash PATH
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
        create: yes
      when: brew_installed.failed

    - name: Add Homebrew to Zsh PATH
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zprofile"
        line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
        create: yes
      when: brew_installed.failed

    - name: Update Homebrew itself
      command: /home/linuxbrew/.linuxbrew/bin/brew update
      when: brew_installed.rc == 0
