---
- name: Install & Configure Rust
  hosts: all
  tasks:
    - name: Check if Rust is installed
      command: rustc --version
      register: rust_check
      ignore_errors: yes

    - name: Install Rust
      shell: |
        asdf plugin add rust https://github.com/code-lever/asdf-rust.git
        asdf install rust latest
        asdf global rust latest

    - name: Check if Rust is installed
      command: rustc --version
      register: rust_check_2
