---
- name: Setup ZSH and p10k Theme
  hosts: all
  tasks:
    - name: Check if ~/.zprofile exists
      stat:
        path: "{{ ansible_env.HOME }}/.zprofile"
      register: zprofile_stat

    - name: Create an empty ~/.zprofile if it does not exist
      file:
        path: "{{ ansible_env.HOME }}/.zprofile"
        state: touch
        mode: '0644'
      when: not zprofile_stat.stat.exists

    - name: Validate the syntax of ~/.zprofile
      command: bash -n "{{ ansible_env.HOME }}/.zprofile"
      when: zprofile_stat.stat.exists
      register: syntax_check
      failed_when: syntax_check.rc != 0
      changed_when: false

    - name: Display syntax validation result
      debug:
        msg: "Syntax check passed, no errors found in ~/.zprofile."
      when: syntax_check.rc == 0

    - name: Display syntax errors if validation fails
      debug:
        msg: "Syntax check failed for ~/.zprofile. Please correct the errors and re-run the playbook."
      when: syntax_check.rc != 0
      failed_when: syntax_check.rc != 0

    - name: Get Homebrew prefix
      shell: brew --prefix
      register: brew_prefix

    - name: Set Zsh location
      set_fact:
        zsh_location: "{{ brew_prefix.stdout }}/bin/zsh"

    - name: Ensure Zsh is in the list of shells
      lineinfile:
        path: /etc/shells
        line: "{{ zsh_location }}"
        create: yes

    - name: Get current shell of the user
      command: echo $SHELL
      register: current_shell

    - name: Set default shell to zsh
      user:
        name: "{{ ansible_env.USER }}"
        shell: "{{ zsh_location }}"
      when: current_shell.stdout != zsh_location

    - name: Check if oh-my-zsh is installed
      stat:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh"
      register: oh_my_zsh_stat

    - name: Install oh-my-zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
      when: not oh_my_zsh_stat.stat.exists

    - name: Check if p10k is already installed
      stat:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
      register: p10k_check

    - name: Install PowerLevel10k Theme
      git:
        repo: 'https://github.com/romkatv/powerlevel10k.git'
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
      when: not p10k_check.stat.exists

    - name: Check if Powerlevel10k theme is configured
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
        create: yes

    - name: Source .zprofile in .zshrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: '. ~/.zprofile'
        create: yes
